### ISSUE TITLE
How to receive : Trophies: Your playstation trophy level Additional attributes are available which breakdown your trophy stats

### ISSUE THREAD

**Issue by reimargithub** [JackJPowell/hass-psn#9]
Hi there,
could you describe how to get the additional attributes ? I only receive my trophy level.
Maybe you can also share your YAML Code of your example on the Github page.
Best Regards
Reimar

**Comment by xXREDXIIIIXx** [comment]
This would be an example code to use for getting the attribute platinum trophies: 
{{ state_attr('sensor.playstation_trophy_level', 'platinum') }}

You might want to try using helpers: **YOUR LINK**/config/helpers

+ New Helper > Template > Template a Sensor -

**EXAMPLE:**
Name: Platinum Trophies
State template*: {{ state_attr('sensor.playstation_trophy_level', 'platinum') }}
leave everything else blank, you should see the preview at the bottom.

once done, you will have a new sensor, as exampled above it will be "sensor.platinum_trophies". you can call this directly instead of needing to use the code.

**Comment by reimargithub** [comment]
Perfect Solution. Thank you (also for the quick response) :)
